### ISSUE TITLE
Get proper PCRaster icon and use in plugin

### ISSUE THREAD

**Issue by nyalldawson** [jvdkwast/qgis-processing-pcraster#10]

**Comment by nyalldawson** [comment]
@jvdkwast I've assigned this to you for now, but I'll do that actual code update as soon as we get the icon

**Comment by jvdkwast** [comment]
@OliverSchmitz will provide the icon in SVG format

**Comment by OliverSchmitz** [comment]
this is a plain SVG, I hope it is ok this way
[pcraster.zip](https://github.com/jvdkwast/qgis-processing-pcraster/files/7092883/pcraster.zip)

**Comment by nyalldawson** [comment]
@OliverSchmitz that format is fine, but unfortunately the rectangular shape of the logo means that it becomes unreadably small when resized down to icon size. 

Do you have any objections to a shortened version with just "PCR" characters for use an icon? E.g. something like:
![image](https://user-images.githubusercontent.com/1829991/131754167-5d38a194-4a75-4e1e-a54f-54477cf2120e.png)

**Comment by OliverSchmitz** [comment]
yes,for an icon the PCR version should be fine. Do you generate it from the existing logo, or shall I make a separate SVG?

**Comment by OliverSchmitz** [comment]
just in case...
[favicon.zip](https://github.com/jvdkwast/qgis-processing-pcraster/files/7103778/favicon.zip)
