### ISSUE TITLE
Publish on QGIS plugin repo

### ISSUE THREAD

**Issue by nyalldawson** [jvdkwast/qgis-processing-pcraster#11]

**Comment by nyalldawson** [comment]
@jvdkwast I think we're good to go now -- want me to push to the plugin repo?

**Comment by jvdkwast** [comment]
Great. Yes!

**Comment by nyalldawson** [comment]
And it's done: https://plugins.qgis.org/plugins/pcraster_tools/ !! Will hit the plugin repos shortly...
