### ISSUE TITLE
Flesh out plugin metadata

### ISSUE THREAD

**Issue by nyalldawson** [jvdkwast/qgis-processing-pcraster#14]
@jvdkwast are you able to edit https://github.com/jvdkwast/qgis-processing-pcraster/blob/main/pcraster_tools/metadata.txt and flesh out the description, tags, and other areas with nicer content?

**Comment by nyalldawson** [comment]
Specifically the "description", "About" and "tags" settings could do with refinement!

**Comment by jvdkwast** [comment]
#18

**Comment by jvdkwast** [comment]
@OliverSchmitz I think that the homepage URL in metadata.txt should point to a new page on the PCRaster website where I can write installation instructions. Can you prepare a page that I can edit or should I send you the text?

**Comment by nyalldawson** [comment]
@jvdkwast I'd suggest we don't use the main PCRaster site there, and instead create a specific homepage for the QGIS plugin (which then in turn links to the main page, but also has instructions on how to install pcraster for qgis, how the plugin works, etc.)
