### ISSUE TITLE
QGIS crashes on closing

### ISSUE THREAD

**Issue by jvdkwast** [jvdkwast/qgis-processing-pcraster#35]
After installing the PCRaster Tools pluging, QGIS crashes at closing. This was observed for different QGIS versions using OSGeo4W as well as Conda installations. It also occured with the original resource sharing tools. It also occurs when no tool is used.

Here's a copy of the crash report:
Crash ID: 2bba35ac54ec3f66db08369439704d5a7beb5523

Stack Trace

GDALDestroyDriver :
dal::GDALRasterDriver::deregisterGDALDrivers :
dal::Client::~Client :
calc::DataStorageId::setId :
::operator() :
__crt_seh_guarded_call::operator(), &, > :
execute_onexit_table :
calc::vs2CsfVs :
calc::vs2CsfVs :
LdrpCallInitRoutine :
LdrShutdownProcess :
RtlExitUserProcess :
ExitProcessImplementation :
exit_or_terminate_process :
common_exit :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.0-Bia?owie?a
QGIS code revision: d9022691f1
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by nyalldawson** [comment]
This is an issue in pcraster itself -- I suspect it's happening because QGIS has already degistered all the GDAL drivers itself.

**Comment by jvdkwast** [comment]
@OliverSchmitz Anything we can do about this?

**Comment by OliverSchmitz** [comment]
most likely related: https://github.com/pcraster/pcraster/issues/343

**Comment by jvdkwast** [comment]
@OliverSchmitz I've tested PCRaster 4.3.3 on Windows with Conda (QGIS 3.18.3) and an OSGeo4W (QGIS 3.22.4 & 3.24.0). QGIS still crashes on exit.
The message in the crash report is different, with some references to PCRaster. Maybe it helps to find the cause?

Crash report for QGIS 3.22.4:

Crash ID: [1f9631ee732fe1c494a262e8ba577ae9da0fdb62](https://github.com/qgis/QGIS/search?q=1f9631ee732fe1c494a262e8ba577ae9da0fdb62&type=Issues)


Stack Trace


GDALDestroyDriver :
dal::GDALRasterDriver::deregisterGDALDrivers :
dal::Client::~Client :
pcraster::python::Globals::setRandomSeed :
::operator() :
__crt_seh_guarded_call::operator(), &, > :
execute_onexit_table :
pcraster::python::Globals::setRandomSeed :
pcraster::python::Globals::setRandomSeed :
LdrpCallInitRoutine :
LdrShutdownProcess :
RtlExitUserProcess :
ExitProcessImplementation :
exit_or_terminate_process :
common_exit :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.22.4-Bia?owie?a
QGIS code revision: ce8e65e9
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

----

Crash report for QGIS 3.24.0
Python Stack Trace
Windows fatal exception: access violation

Current thread 0x000043d0 (most recent call first):



Stack Trace
No stack trace is available.


QGIS Info
QGIS Version: 3.24.0-Tisler
QGIS code revision: 6b44a42058
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

**Comment by elirober** [comment]
I installed PCRaster (and the associated plugin) as instructed in on pages 89-90 in Hans's book QGIS for Hydrological Applications, and I also now have the "QGIS unexpectedly ended" when I exit QGIS. The Crash ID and Stack Trace are copied below:

Crash ID: [df7ab36d97299e20a77faa2780932f1ee15ee61c](https://github.com/qgis/QGIS/search?q=df7ab36d97299e20a77faa2780932f1ee15ee61c&type=Issues)


Stack Trace


CPLODBCDriverInstaller::RemoveDriver :
dal::GDALRasterDriver::deregisterGDALDrivers :
dal::Client::~Client :
pcraster::python::Globals::setRandomSeed :
::operator() :
__crt_seh_guarded_call::operator(), &, > :
execute_onexit_table :
pcraster::python::Globals::setRandomSeed :
pcraster::python::Globals::setRandomSeed :
LdrpCallInitRoutine :
LdrShutdownProcess :
RtlExitUserProcess :
ExitProcessImplementation :
exit_or_terminate_process :
common_exit :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.22.11-Bia?owie?a
QGIS code revision: 106d33d7
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.2



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

**Comment by jvdkwast** [comment]
After upgrading to PCRaster 4.4.0 I still get the crash message at closing of QGIS 3.22 (both with OSGeo4W installer and conda).
QGIS 3.26 (installed with OSGeo4W) doesn't show the crash anymore.

Here's the crash report from QGIS 3.22.11.

Crash ID: [f7fa77a8ccd087d4de5cfbf53f2030b52933045f](https://github.com/qgis/QGIS/search?q=f7fa77a8ccd087d4de5cfbf53f2030b52933045f&type=Issues)


Stack Trace


CPLODBCDriverInstaller::RemoveDriver :
dal::GDALRasterDriver::deregisterGDALDrivers :
dal::Client::~Client :
calc::DataStorageId::setId :
::operator() :
__crt_seh_guarded_call::operator(), &, > :
execute_onexit_table :
calc::vs2CsfVs :
calc::vs2CsfVs :
LdrpCallInitRoutine :
LdrShutdownProcess :
RtlExitUserProcess :
ExitProcessImplementation :
exit_or_terminate_process :
common_exit :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.22.11-Bia?owie?a
QGIS code revision: 106d33d7
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.2



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

**Comment by jvdkwast** [comment]
I haven't seen this issue in recent versions of PCRaster/QGIS. Shall we close the issue?

**Comment by elirober** [comment]
Yes.. The crash problem on closing has not been experienced in quite some time.
