### ISSUE TITLE
'Column File to PCRaster Map (col2map) generates errors 

### ISSUE THREAD

**Issue by Detritalgeo** [jvdkwast/qgis-processing-pcraster#39]
I am the guy that posted on the YouTube tutorial video. I appreciate your willingness to help.

So I am trying to generate catchments from outlet points across 3,500 km-sq. There are 7891 outlet points that are actually sample points with a 5 digit sample ID. 

I followed your youtube tutorial for how to use PCRaster tools with the QGIS plugin and everything went well except for the col2map procedure. 

![image](https://user-images.githubusercontent.com/49292273/144530880-11be4fd3-93f1-4ea4-bc53-d907cc21a534.png)

With your suggestion I then bypassed the QGIS plugin and used the OSGeo4W shell to run the command. 
After numerous iterations I eventually found that there is a limit of 254 entries in the csv table to be converted to pcraster format. Also an ID of '255' is not a 'legal nominal value in small cell representation' I assume this is a limitation due to the data type established for the outlet ID field (byte?). 

Now as long as my csv table only includes ID's of 1-254 it will execute reliably in the shell but errors persist in QGIS with more erratic behavior. Perhaps restarting QGIS is required. 

It would be ideal if the col2map could intake an ID as a field with a few more numbers (make it an int?) but I assume that means modifying the PCRaster core codebase. 

I hope any of this is helpful but please reach out if any more detail is needed.

QGIS version: 3.16.14 LTR
PCRaster Plugin: 0.1.1
pcraster version: 4.3.1
Windows 10

**Comment by jvdkwast** [comment]
I assume that you are creating a nominal PCRaster map with the col2map tool.
By default PCRaster uses the small integer cell representation, which is limited to 8 bit integer values. You can change this using a global option by typing in the OSGeo4W shell:
`set PCROPTIONS = --large`

Here's the documentation: [https://pcraster.geo.uu.nl/pcraster/4.3.2/documentation/pcraster_manual/sphinx/secimport.html#gorepres](https://pcraster.geo.uu.nl/pcraster/4.3.2/documentation/pcraster_manual/sphinx/secimport.html#gorepres)

**Comment by Detritalgeo** [comment]
Yes, this is selecting the nominal PCRaster map. 

Thanks so much for the suggestion regarding cell representation. I will attempt that now.

Is this a setting that i can modify in the current version of the QGIS plugin?

**Comment by Detritalgeo** [comment]
Thanks for the suggestion. I was not able to figure out the way to set the global parameter for 'large integer' cell representation of nominal data but I was able to figure out that I could add it to the col2map command and that worked. 

This way I was able to preserve the 5-digit numeric sample ID which avoids some headaches (such as processing the outlets in batches of 255 and keeping track of the re-assigned numeric ID's).

This is in the OSGeo4W terminal, not the QGIS processor tool. 

`col2map -N --large outlets.csv outlets.map --clone flowdirection.map`

**Comment by jvdkwast** [comment]
I've also checked now if the solution from the manual that I proposed works and it indeed doesn't work.
Great that you found the way that works!
I'll include the option to choose small and large representation from the QGIS col2map tool in an update soon.

**Comment by Detritalgeo** [comment]
Excellent. Thanks so much.

I also did a little more investigation and determined that my original file paths were too long. The col2map tool plugin now works great but I have to move the reference files so the file path is shorter. I generally have to run the data from a Sharepoint environment with Onedrive synchronization so the file paths can be quite long. 

The other tools work just fine with the longer file paths, just col2map that has the limitation.

**Comment by jvdkwast** [comment]
col2map and resample are PCRaster commands that are not implemented in Python. The plugin calls the command, while with the other tools it executes Python code. That explains the difference in behaviour.
The issue with the long paths is not caused by the plugin and therefore the issue should be posted in the PCRaster repo: [https://github.com/pcraster/pcraster/issues](https://github.com/pcraster/pcraster/issues)
