### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by timlinux** [jvdkwast/qgis-processing-pcraster#42]
When I install the PCRaster plugin it tells me that the pcraster libs need to be available and to consult the plugin docs. I can't find where the docs are - perhaps they can be added to the README, plugin metadata and the warning that pops up saying your libs are missing.

**Comment by jvdkwast** [comment]
You can find the documentation when you click the homepage link in the plugin metadata info presented when you install the plugin.
It leads to this [GitHub pages site](https://jvdkwast.github.io/qgis-processing-pcraster/).
I'll also add that to the readme.

**Comment by timlinux** [comment]
Ah totally missed that link, thanks!
