### ISSUE TITLE
Error code after installing the pcraster plugin

### ISSUE THREAD

**Issue by tariah7** [jvdkwast/qgis-processing-pcraster#48]
i always get this error message "PCRaster Tools Plugin: PCRaster is not installed -- algorithms will not be available" when ever i launch the pcraster plugin, which makes it difficult to run an analysis on QGIS.

![image](https://user-images.githubusercontent.com/31789089/188289579-af63cfac-d4ab-4f19-9967-dcdeb1a3699d.png)

**Comment by jvdkwast** [comment]
The PCRaster Tools plugin is a so called Processing Provider plugin. This means that you have to install both the software (PCRaster) as well as the plugin. Instructions to install PCRaster can be found in the [plugin documentation](https://jvdkwast.github.io/qgis-processing-pcraster/). For troubleshooting your PCRaster installation on windows [check this video](https://youtu.be/2pEr5RoGAXc).

**Comment by tariah7** [comment]
Good evening sir,

I got this error message trying to perform the "flowdir" operation after
converting the DEM to pcraster format.

[image: image.png]

[image: image.png]

**Comment by jvdkwast** [comment]
I can't see the images and please paste the error here too.

**Comment by tariah7** [comment]
Good evening sir,
Please find attached the image.

Best regards.

**Comment by jvdkwast** [comment]
@tariah7 Images are not coming through. I see you reply these comments by e-mail. It's better to go to the GitHub issue page and post your question with images there. Otherwise I can't see them.

**Comment by tariah7** [comment]
Ok, I'll check it out.
