### ISSUE TITLE
Lookup table from RAT - error

### ISSUE THREAD

**Issue by jvdkwast** [jvdkwast/qgis-processing-pcraster#49]
This issue was originally reported in the PCRaster repository, but is not related to PCRaster, but the plugin. Therefore continuing here @GvdDool.
[https://github.com/pcraster/pcraster/issues/364#issue-1379436411](https://github.com/pcraster/pcraster/issues/364#issue-1379436411)

I'll check it as soon as I have time. Meanwhile check these videos to see if you're using the tool correctly: 

- [Create lookup tables from a Raster Attribute Table and reclassify raster using PCRaster in QGIS](https://youtu.be/JzFVumsJhHk)
- [Create Lookup Tables from Raster Attribute Tables of Continuous Rasters using PCRaster in QGIS](https://youtu.be/8HEOm4XWrVk)

**Comment by jvdkwast** [comment]
@GvdDool, please describe exactly the steps that you did. If possible also add the data that you have used.

**Comment by GvdDool** [comment]
Sorry, Hans, for my late reaction; I was travelling.

The problem is that I have a land use / land cover dataset (ESA_World_Cover) clipped over a project area:
```
Width	7725
Height	6657
Data type	Float32 - Thirty two bit floating point
GDAL Driver Description	GTiff
```

Which I convert to:
```
Width	7725
Height	6657
Data type	Int32 - Thirty two bit signed integer 
GDAL Driver Description	PCRaster
GDAL Driver Metadata	PCRaster Raster File
#int32 is fine, as the data start at 0 and ends at 95, but now I don't have a RAT
```

On this PCRaster Raster File, I try to generate a **Lookup table from RAT**, and get the following error:

```
Input parameters:
{ 'INPUT' : 'E:/Projects/ESA_World_Cover_Clip2.map', 'OUTPUT' : 'E:/Projects/testLULC.csv' }

Traceback (most recent call last):
File "C:\Users/RueDuMidi_G/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pcraster_tools\processing\algorithms\lookuptablefromrat.py", line 139, in processAlgorithm
self.to_csv(rat, output_lookup_table, table_type)
File "C:\Users/RueDuMidi_G/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pcraster_tools\processing\algorithms\lookuptablefromrat.py", line 82, in to_csv
col_count = rat.GetColumnCount()
AttributeError: 'NoneType' object has no attribute 'GetColumnCount'

Execution failed after 0.10 seconds
```
which is logic, as there is **no longer a RAT**

So, I tried to create any PCRaster format to work with this data, but none of the conversions gave me access to the RAT, and using the nominal data set (as only format which makes sense for this data) generated the error above.

On the original data I have a RAT, but then I get this:
```
Algorithm 'Lookup table from RAT' starting…
Input parameters:
{ 'INPUT' : 'E:/Projects/ESA_World_Cover_Clip.tif', 'OUTPUT' : 'E:/Projects/testLULC.csv' }

Traceback (most recent call last):
File "C:\Users/RueDuMidi_G/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pcraster_tools\processing\algorithms\lookuptablefromrat.py", line 134, in processAlgorithm
if metadata['PCRASTER_VALUESCALE'] == 'VS_SCALAR':
KeyError: 'PCRASTER_VALUESCALE'

Execution failed after 0.05 seconds

Loading resulting layers
```

<img width="703" alt="image" src="https://user-images.githubusercontent.com/54751004/192872926-5187f7ab-3240-47b5-ab9b-40c287c09b78.png">

**Comment by jvdkwast** [comment]
@GvdDool In your description I miss the step where you edit the RAT to contain the reclassification values. I also miss that you have used the Layer Styling panel to style the PCRaster layer and the RAT will be created. Please confirm if you have watched the videos I mentioned above and indicate where your procedure deviates.

**Comment by GvdDool** [comment]
I see, let me try to style the *.map layer, because this is indeed a step I missed, and test on the created RAT, hoping not to see the same error as when working on the first (*.tif) layer.

**Comment by GvdDool** [comment]
Correcting the RAT table as in the video

![image](https://user-images.githubusercontent.com/54751004/193007221-66f3a15a-5baa-4049-b185-b9deccff882b.png)

and then run the tool as in the instruction video:
```
Algorithm 'Lookup table from RAT' starting…
Input parameters:
{ 'INPUT' : 'E:/Projects/ESA_World_Cover_Clip2.map', 'OUTPUT' : 'E:/Projects/testLULC.csv' }

Traceback (most recent call last):
File "C:\Users/RueDuMidi_G/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pcraster_tools\processing\algorithms\lookuptablefromrat.py", line 139, in processAlgorithm
self.to_csv(rat, output_lookup_table, table_type)
File "C:\Users/RueDuMidi_G/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pcraster_tools\processing\algorithms\lookuptablefromrat.py", line 82, in to_csv
col_count = rat.GetColumnCount()
AttributeError: 'NoneType' object has no attribute 'GetColumnCount'

Execution failed after 0.28 seconds

Loading resulting layers
Algorithm 'Lookup table from RAT' finished
```

**Comment by jvdkwast** [comment]
The last 2 rows of your lookup table are not correct (your right screenshot), probably some issue with sorting the columns?
If you open the CSV output in a text editor, I assume it looks now like:
```
[0,10] 0
<10,20] 10
<20,30] 20
<30,40] 30
<40,50] 40
<50,60] 50
<60,70] 60
<70,80] 70
<80,90] 80
<90,3.40282e23] 90
<95,0] 95
```
This will not work.
Try to correct the RAT or you can edit the last lines of the CSV. If it's correct you can use it from the QGIS Python console:
```Python
from pcraster import *
Landuse = readmap("E:/Projects/ESA_World_Cover_Clip2.map")
LookupTable = "E:/Projects/testLULC.csv"
Result = lookupnominal(LookupTable,Landuse)
report(Result,"E:/Projects/result.map")
```
Then drag the `result.map` file from the browser panel to the map canvas to see the result.

**Comment by GvdDool** [comment]
Hi Hans, 
The E:/Projects/testLULC.csv' file is empty, the code breaks before writing:
AttributeError: 'NoneType' object has no attribute 'GetColumnCount'

I can manually construct the lookup table and apply the lookup function, which is already a great help (coming from an ESRI environment where this is done much easier). 

I noticed the error in the two lines too late, the original line ">90" and the inserted line with "95"; I don't think that there is a class 95: mangroves in my project area, but that's what the original legend is using.

**Comment by GvdDool** [comment]
I changed the RAT to:
<img width="320" alt="image" src="https://user-images.githubusercontent.com/54751004/193038207-3ec98197-00b2-4631-952c-df80f5142dbe.png">

but the error is the same.

**Comment by jvdkwast** [comment]
If you want an easy "ESRI" like solution, use the native [Reclassify by table](https://docs.qgis.org/3.22/en/docs/user_manual/processing_algs/qgis/rasteranalysis.html#qgisreclassifybytable) tool from the Processing Toolbox.
Here's a video: [https://youtu.be/s7KrIjvcCz0](https://youtu.be/s7KrIjvcCz0).

Without data sample I can't reproduce your issue with the Lookup table from RAT tool. Maybe this alternative works for you.

**Comment by GvdDool** [comment]
Let me try to get a sample of the data, the full set is a bit large to send through github, I liked the RAT-to-table option, so I hope that this will work somehow - it's just a bit strange that the error points to the RAT table, with: col_count = rat.GetColumnCount()

Attached an subset of my data, generating the errors I see, as well as the log file:
[For_HansError01.zip](https://github.com/jvdkwast/qgis-processing-pcraster/files/9675239/For_HansError01.zip)

**Comment by jvdkwast** [comment]
I see in the zipfile that you have ESA_clip.map.vat.dbf
Note that you need to choose the **GDAL Auxilary XML** format and not the **VAT DBF** format. This was mentioned in the video, but I'll also add it to the help text of the tool. Please check if this was indeed the problem. The tool only works with the GDAL XML file.

**Comment by GvdDool** [comment]
Thanks Hans,
That worked like a charm!

```
Algorithm 'Lookup table from RAT' starting…
Input parameters:
{ 'INPUT' : 'E:/Projects/For_Hans/ESA_clip.map', 'OUTPUT' : 'E:/Projects/For_Hans/testLookup2.csv' }

Execution completed in 0.08 seconds
Results:
{'OUTPUT': 'E:/Projects/For_Hans/testLookup2.csv'}

Loading resulting layers
Algorithm 'Lookup table from RAT' finished
```
