### ISSUE TITLE
PCRaster 

### ISSUE THREAD

**Issue by EzatArefDahoah** [jvdkwast/qgis-processing-pcraster#60]
![image](https://github.com/jvdkwast/qgis-processing-pcraster/assets/167071136/4b345f60-68b5-4d17-aae1-69164dd0750e)
I have installed PCraster from inside Qgis also from ZIP and from OSGeo4w app but it still appear this warning PCraster is not installed, although the icon for PCraster is appearing in the processing toolbox . and when conducting an analysis for a model  it says PCraster library is not installed .
![image](https://github.com/jvdkwast/qgis-processing-pcraster/assets/167071136/462b241a-470e-4f5f-8d6a-bfb64480d442)

Could you please support me in solving this ?

**Comment by jvdkwast** [comment]
You might have different installations of QGIS  in parallel. Each installation is linked to an OSGeo4W installer.
You need to close QGIS first in order to run the installer. I see in the first screenshot that you could run the installer without closing QGIS. This might be because you're using an installer from another installation.
[Watch this video](https://youtu.be/2pEr5RoGAXc?si=bFnh1mHd_ItjJdao&t=29) to find the correct installer. I hope this helps.

**Comment by EzatArefDahoah** [comment]
Yeah, dear Kwast.
![image](https://github.com/jvdkwast/qgis-processing-pcraster/assets/167071136/7003c204-2ce9-4efb-a045-c810a9bb951a)

I could not access the setup on the file location of Qgis because my laptop is rleated to the Org. so I installed the Osgeo4w app and tried to run it . is that the cause of this error, i mean do i have to use the setup on the file location of qgis?
![image](https://github.com/jvdkwast/qgis-processing-pcraster/assets/167071136/b0f402ba-247c-47f6-9e5e-6beff5db8a86)

**Comment by jvdkwast** [comment]
You have to use the setup in the location where you have the installation of the QGIS that you are using. If you use another one it can't work. Maybe you need to click right to run it as administrator.

**Comment by jvdkwast** [comment]
@EzatArefDahoah, did you solve the issue?

**Comment by GuoZengkun0201** [comment]
I have installed PCraster from inside QGIS, but I found a red warnning"PCRaster Tools Plugin: PCRster is not installed -- algorithms will not be available". Then, I clicked "Details", and then a picture appeared。“PCRaster must be installed and available in the current Python environment before the PCRaster algorithms can be used. Please see the [plugin documentation](https://jvdkwast.github.io/qgis-processing-pcraster/) for further details on how to install PCRaster.”
How can this problem be solved, please? @jvdkwast 
![1722143284726](https://github.com/user-attachments/assets/82d74e53-fb18-4fba-a306-a875f52d1063)

**Comment by jvdkwast** [comment]
@GuoZengkun0201, you need to follow the instructions in the [documentation](https://jvdkwast.github.io/qgis-processing-pcraster/) to install PCRaster.
In the documentation, you see instructions for several operating systems. Look at the section where you can find your operating system and follow the instructions.

**Comment by GuoZengkun0201** [comment]
Thanks for the advice you provided, I went through the steps again according to my computer system and conditions, this time without the red warning message, so maybe it worked. @jvdkwast
I am currently working on the Surface Energy Balance System (SEBS) model, and I have read some of your literature. Can you share some tutorials on this, as I am currently confused as to how to implement evapotranspiration calculations using the PC Raster. I hope you can provide some help, thanks!

**Comment by jvdkwast** [comment]
@GuoZengkun0201. Great that you succeeded with the installation.
Note that that was the procedure to use the PCRaster Tools plugin in QGIS.
SEBS has been implemented by me a long time ago using the PCRaster Python package (which you now have installed too, but you can use it outside of QGIS or in the QGIS Python Console). The code of SEBS is in another repository, so please add your issues there: [https://github.com/jvdkwast/PySEBS](https://github.com/jvdkwast/PySEBS). Note that I don't maintain that code anymore and there are no tutorials.

**Comment by GuoZengkun0201** [comment]
Thank you, sir @jvdkwast
I will try it.
