### ISSUE TITLE
PCRaster plugins not working after being installed even though I did the OSGeo4w thing previously

### ISSUE THREAD

**Issue by Crones8** [jvdkwast/qgis-processing-pcraster#61]
Hello,

Version of QGIS is 3.28.10.

I've seen this issue being asked here in github before:

![image](https://github.com/user-attachments/assets/d2430536-2ad7-4bc7-b3e2-b88d2ea03209)

Tried the PCraster main github page, and they asked me to try to get answers here.

Mostly people are redirected to https://jvdkwast.github.io/qgis-processing-pcraster/, in which the installation of PCRaster through OSGeo4w is suggested (watched the video and everything):

![image](https://github.com/user-attachments/assets/6868c0f0-06af-4295-907a-fe63aec3fdc4)

I already did this, and succesfully, as shown here:

![image](https://github.com/user-attachments/assets/7f10cd71-157f-492d-b433-5f15aacac1ef)

So, even though I've followed the suggested troubleshooting steps, software still will not work.

Please Help

**Comment by jvdkwast** [comment]
Please check if the installer corresponds with the QGIS instance you're using. Each instance has its own OSGeo4W installer, unless you have installed it from the same installer.

**Comment by Crones8** [comment]
Hello @jvdkwast , thank you for answering,

Which installer are you referring to? I think it's the OSGeo4W installer you are talking about, if so:

I believe it should be the same instance, since I started the OsGeo4W from the same folder that has this version of QGIS:

![image](https://github.com/user-attachments/assets/3aabf497-bfe3-4528-9ee9-fecf19a17bac)

Cheers and thank you.

**Comment by Crones8** [comment]
Hello?

Tried also the option in the video which would be this:

![image](https://github.com/user-attachments/assets/bab14933-75fc-40eb-8bf4-c3538dbf984e)

No luck though.

Cheers.

**Comment by jvdkwast** [comment]
Please contact me by e-mail (hans@qwast-gis.com) to make an appointment for a call. I'll then talk you through.

**Comment by jvdkwast** [comment]
I had a call and we could solve the issue.

**Comment by Crones8** [comment]
So, to anyone asking how we "fixed" this, here it is:

The reason I say "fixed" it's because Hans helped me to get 2 instances of QGIS working in my PC 3.28.10 and 3.40.1 (without uninstalling either one), and now I can effectively use PCRaster Tools on 3.40.1, however, I couldn't get it to work in 3.28.10, so yeah, I can now use PCRaster Tools, just not on the older version of QGIS.

Hans tells me it's probably because the version of PCRaster that is installed through OSGeo4W only works with the latest or some of the latest version of QGIS, and not with legacy versions, though this is not proved yet.

Hope this helps anyone, and special thanks to Hans for taking the time, even while being on a trip, to help me, he is truly a person who cares to help.
