### ISSUE TITLE
Setup documentation workflow

### ISSUE THREAD

**Issue by nyalldawson** [jvdkwast/qgis-processing-pcraster#9]

**Comment by nyalldawson** [comment]
@jvdkwast I'll need to do a video call with you to talk you through setting this up on the github repo. Can you email me when you're online and available for this?

**Comment by jvdkwast** [comment]
The [GitHub page](https://jvdkwast.github.io/qgis-processing-pcraster/) now points to readme.md instead of website/pages/index.md

**Comment by nyalldawson** [comment]
@jvdkwast the workflow should be working ok now -- can you set the repo settings for github pages to use the gh-pages branch again? (Like we were trying to do earlier)

**Comment by jvdkwast** [comment]
@nyalldawson Done. The page shows up now.
The only thing is that the numbered lists are not taken over correctly from the index.md file.

**Comment by nyalldawson** [comment]
@jvdkwast that's fixed now
